[package]
name = "tree-edit-distance"
version = "0.1.0"
edition = "2018"
authors = ["Kai Frerich <kai.frerich@rwth-aachen.de>"]

[lib]
name = "tree_edit_distance"

[dependencies]
nalgebra = "0.19.0"
